"""Check every document against docs/conventions.md, and against the run logs.

    python scripts/check_docs.py            # report problems, exit 1 if any
    python scripts/check_docs.py --list     # also list what was checked

Documentation is written from these files by people who will not re-derive the numbers, so a stale
claim or a mistyped Dice figure propagates straight into the paper. Three classes of error are
caught here because all three have actually happened in this project:

1. **Retracted claims reappearing.** The "3D reversal", the BatchNorm-statistics explanation, and
   the averaging-based outlier mechanism were each stated confidently and later refuted. Files that
   still assert them must carry a superseded banner.
2. **Numbers drifting from the logs.** Every headline Dice figure in the current documents is
   re-derived from `artifacts/` here and compared. A document that disagrees with the frozen
   snapshots is wrong by definition.
3. **The hospital/hypothesis name collision.** `H1`-`H4` are hospitals in the data; `H1`-`H3` are
   hypotheses. Current documents must use Site A-D in prose so the two can never be confused.
"""

from __future__ import annotations

import argparse
import json
import re
import statistics
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DOCS = REPO / "docs"

# Documents that describe v1 and are deliberately frozen. They may contain retracted claims and
# H1-H4 hospital columns, provided they say so at the top.
SUPERSEDED = {"project_report.md", "project_status_report.md", "capstone_project_report.md"}
# docs/ holds the four current documents; everything historical lives under archive/ and
# everything tool-written lives under results/. Both are exempt from the prose rules.
ARCHIVE = DOCS / "archive"
RESULTS = DOCS / "results"
BANNER = "Superseded"

# Generated by scripts; not hand-maintained prose, so exempt from the naming rule.
GENERATED = re.compile(r"^results-(comparison|inference-only|training-effect|significance)")

RETRACTED = [
    (re.compile(r"hypothesis outcomes REVERSE|all three .{0,30}reverse", re.I),
     'the "all three verdicts reverse in 3D" claim'),
    (re.compile(r"insufficient to estimate stable 3D batch", re.I),
     "the BatchNorm-statistics explanation for FedBN in 3D"),
    (re.compile(r"monotone.{0,40}averaging|ordered .{0,30}by how much .{0,20}averaging", re.I),
     "the averaging-ordering outlier mechanism"),
]

# Claims that must never appear unqualified, because the margin is not significant.
OVERCLAIM = re.compile(r"FedBN (wins|beats FedAvg) in 3D", re.I)

# A negated mention ("it does not follow that FedBN wins in 3D") is the correct way to write
# this, so only an unqualified assertion counts as a problem.
NEGATION = re.compile(r"\bnot\b|\bnever\b|\bavoid\b|rather than", re.I)


def all_docs() -> list[Path]:
    """Every markdown file under docs/, including results/ and archive/."""
    return sorted(DOCS.rglob("*.md"))


def window(tag: str) -> set[int]:
    return set(range(36, 41)) if tag in {"v4", "v5"} else set(range(21, 26))


def mean_wt(tag: str, meth: str, dim: str, seed: int = 42) -> float | None:
    """Mean diagonal WT Dice over the estimator window, straight from the run log."""
    root = REPO / "artifacts" / "snapshots" / tag
    p = root / f"{meth}_{dim}_{seed}" / "metrics.jsonl"
    if not p.exists():
        return None
    rs, byr = window(tag), {}
    for line in p.open():
        r = json.loads(line)
        if r.get("stage", "round") != "round" or r["split"] != "test":
            continue
        if not (r["model_hospital"] == "global" or r["model_hospital"] == r["test_hospital"]):
            continue
        if r["round"] in rs:
            byr.setdefault(r["round"], []).append(r["dice_wt"])
    if not byr:
        return None
    return statistics.fmean(statistics.fmean(v) for v in byr.values())


# Headline figures quoted in the current documents, and where they come from.
FACTS = [
    ("v5", "centralized", "2d", 0.8954), ("v5", "local", "2d", 0.8699),
    ("v5", "fedavg", "2d", 0.8629),      ("v5", "fedbn", "2d", 0.8756),
    ("v5", "centralized", "3d", 0.8879), ("v5", "local", "3d", 0.8527),
    ("v5", "fedavg", "3d", 0.8618),      ("v5", "fedbn", "3d", 0.8642),
    ("v1", "centralized", "2d", 0.8582), ("v1", "local", "2d", 0.8436),
    ("v1", "fedavg", "2d", 0.8502),      ("v1", "fedbn", "2d", 0.8514),
    ("v1", "centralized", "3d", 0.8768), ("v1", "local", "3d", 0.8490),
    ("v1", "fedavg", "3d", 0.8525),      ("v1", "fedbn", "3d", 0.8422),
]


def check_numbers(problems: list[str], checked: list[str]) -> None:
    for tag, meth, dim, quoted in FACTS:
        actual = mean_wt(tag, meth, dim)
        if actual is None:
            problems.append(f"NUMBERS  no log found for {tag}/{meth}_{dim}_42 — cannot verify {quoted}")
            continue
        if abs(actual - quoted) > 5e-5:
            problems.append(
                f"NUMBERS  {tag} {meth} {dim}: documents quote {quoted:.4f}, "
                f"logs give {actual:.4f}")
        checked.append(f"{tag} {meth} {dim} = {actual:.4f}")


def check_docs(problems: list[str], checked: list[str]) -> None:
    for path in sorted(all_docs()):
        name = path.name
        if name == "conventions.md":
            continue
        archived = ARCHIVE in path.parents
        generated = RESULTS in path.parents
        text = path.read_text(encoding="utf-8", errors="replace")
        superseded = BANNER in text[:1500] or archived
        checked.append(f"{name}{' (superseded)' if superseded else ''}")

        for pattern, what in RETRACTED:
            if pattern.search(text) and not superseded:
                problems.append(
                    f"RETRACTED  {name} asserts {what} without a superseded banner")

        for m in OVERCLAIM.finditer(text):
            before = text[max(0, m.start() - 60):m.start()]
            ctx = text[max(0, m.start() - 400):m.end() + 400]
            # A negated mention ("it does not follow that FedBN wins in 3D") is the correct way to
            # write this, so only an unqualified assertion is a problem.
            negated = re.search(NEGATION, before)
            qualified = "not significant" in ctx or "no significant difference" in ctx
            if not (negated or qualified):
                problems.append(
                    f"OVERCLAIM  {name} says \"{m.group(0)}\" without the "
                    f"non-significance qualifier")

        if name in SUPERSEDED and not superseded:
            problems.append(f"BANNER  {name} is superseded but carries no banner")

        # Naming: a hospital column header in current prose must use Site names.
        if not superseded and not generated and not GENERATED.match(name):
            if re.search(r"\|\s*H1\s*\|\s*H2\s*\|\s*H3\s*\|\s*H4\s*\|", text):
                problems.append(
                    f"NAMING  {name} has an H1|H2|H3|H4 hospital column — use Site A-D "
                    f"(see conventions.md)")


LINK = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")


def anchor_of(heading: str) -> str:
    """GitHub's heading-to-anchor rule: lowercase, drop punctuation, spaces to hyphens.

    Each space becomes its own hyphen -- GitHub does not collapse runs. It matters wherever
    punctuation sat between two words ("shift -- the source" leaves two spaces behind once the
    dash is dropped, and the anchor really does carry two hyphens there).
    """
    a = heading.strip().lstrip("#").strip().lower()
    a = re.sub(r"[^\w\s-]", "", a)
    return re.sub(r"\s", "-", a)


def check_links(problems: list[str], checked: list[str]) -> None:
    """Every relative link between documents must resolve, anchors included.

    Renaming a section silently breaks every link into it, and a reader following a dead anchor
    lands at the top of a long document with no idea what they were meant to read.
    """
    anchors: dict[str, set[str]] = {}
    for path in all_docs():
        text = path.read_text(encoding="utf-8", errors="replace")
        anchors[path.name] = {anchor_of(h) for h in re.findall(r"^#{1,6} .+$", text, re.M)}

    for path in sorted(all_docs()):
        text = path.read_text(encoding="utf-8", errors="replace")
        for target in LINK.findall(text):
            if target.startswith(("http://", "https://", "mailto:", "#")):
                continue
            file_part, _, anchor = target.partition("#")
            if not file_part:
                continue
            dest = (path.parent / file_part).resolve()
            if not dest.exists():
                problems.append(f"LINK  {path.name} -> {target} (file not found)")
                continue
            if anchor and dest.name in anchors and anchor not in anchors[dest.name]:
                problems.append(f"LINK  {path.name} -> {target} (anchor not found)")
            checked.append(f"link {path.name} -> {target}")


ITERATIONS = {"v1": 14, "v2": 14, "v3": 8, "v4": 1, "v5": 8}


def check_snapshots(problems: list[str], checked: list[str]) -> None:
    """Every iteration must be archived under artifacts/snapshots/<vN>/ with a manifest.

    The archive is the evidence base -- artifacts/runs/ is git-ignored working state that exists
    on one laptop. An iteration referenced by the documentation but missing from snapshots is a
    claim with nothing behind it.
    """
    root = REPO / "artifacts" / "snapshots"
    if not root.exists():
        problems.append("SNAPSHOT  artifacts/snapshots/ is missing entirely")
        return
    for tag, expected in ITERATIONS.items():
        d = root / tag
        if not d.is_dir():
            problems.append(f"SNAPSHOT  artifacts/snapshots/{tag}/ missing")
            continue
        if not (d / "MANIFEST.json").exists():
            problems.append(f"SNAPSHOT  {tag} has no MANIFEST.json — it is not hash-verified")
            continue
        runs = [p for p in d.iterdir() if p.is_dir()]
        if len(runs) != expected:
            problems.append(
                f"SNAPSHOT  {tag} holds {len(runs)} runs, expected {expected}")
        checked.append(f"snapshot {tag}: {len(runs)} runs")


def check_review_pack(problems: list[str], checked: list[str]) -> None:
    """If the review pack exists, it must not be older than the documents it copies.

    The pack is what gets opened in front of a reviewer, and it holds *copies*. A doc edited
    after the pack was built leaves a stale copy that still reads as authoritative -- exactly the
    failure this whole checker exists to prevent, just one directory over.
    """
    pack = REPO / "review"
    if not pack.exists():
        return
    built = pack / "README.md"
    if not built.exists():
        problems.append("REVIEW  review/ exists but has no README.md — rebuild it")
        return
    stamp = built.stat().st_mtime
    stale = [p.name for p in DOCS.glob("*.md") if p.stat().st_mtime > stamp]
    if stale:
        problems.append(
            f"REVIEW  review/ is older than {len(stale)} document(s) "
            f"({', '.join(sorted(stale)[:3])}{'…' if len(stale) > 3 else ''}) — "
            f"rerun: python scripts/build_review_pack.py")
    checked.append(f"review pack: {len(list(pack.rglob('*.md')))} documents, "
                   f"{'stale' if stale else 'current'}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--list", action="store_true", help="also print what was checked")
    args = ap.parse_args()

    problems: list[str] = []
    checked: list[str] = []
    check_numbers(problems, checked)
    check_docs(problems, checked)
    check_links(problems, checked)
    check_snapshots(problems, checked)
    check_review_pack(problems, checked)

    if not (DOCS / "conventions.md").exists():
        problems.append("MISSING  docs/conventions.md — the canonical naming reference")

    if args.list:
        print("checked:")
        for c in checked:
            print(f"  {c}")
        print()

    if problems:
        print(f"{len(problems)} problem(s):\n")
        for p in problems:
            print(f"  {p}")
        return 1
    print(f"docs consistent — {len(FACTS)} figures re-derived from logs, "
          f"{len(all_docs())} documents checked")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
